// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ezjob

import (
	"github.com/jackie8tao/ezjob/internal/pkg/cluster"
	"github.com/jackie8tao/ezjob/internal/pkg/dispatcher"
	"github.com/jackie8tao/ezjob/internal/pkg/event"
	"github.com/jackie8tao/ezjob/internal/pkg/extcron"
	"github.com/jackie8tao/ezjob/internal/pkg/server"
	"github.com/jackie8tao/ezjob/internal/pkg/watcher"
	"github.com/jackie8tao/ezjob/proto"
)

// Injectors from wire.go:

func nodeProvider(cfg *proto.AppConfig) *cluster.Node {
	etcdConfig := newEtcdCfg(cfg)
	client := newEtcdCli(etcdConfig)
	manager := event.NewManager()
	node := cluster.NewNode(client, manager)
	return node
}

func watcherProvider(cfg *proto.AppConfig) *watcher.Watcher {
	etcdConfig := newEtcdCfg(cfg)
	client := newEtcdCli(etcdConfig)
	manager := event.NewManager()
	watcherWatcher := watcher.NewWatcher(client, manager)
	return watcherWatcher
}

func reporterServerProvider(cfg *proto.AppConfig) *server.ReporterServer {
	grpcConfig := newGrpcCfg(cfg)
	etcdConfig := newEtcdCfg(cfg)
	client := newEtcdCli(etcdConfig)
	mysqlConfig := newMysqlCfg(cfg)
	db := newGormDB(mysqlConfig)
	reporterServer := server.NewReporterServer(grpcConfig, client, db)
	return reporterServer
}

func adminServerProvider(cfg *proto.AppConfig) *server.AdminServer {
	httpConfig := newHttpCfg(cfg)
	etcdConfig := newEtcdCfg(cfg)
	client := newEtcdCli(etcdConfig)
	adminServer := server.NewAdminServer(httpConfig, client)
	return adminServer
}

func schedProvider(cfg *proto.AppConfig) *extcron.Scheduler {
	etcdConfig := newEtcdCfg(cfg)
	client := newEtcdCli(etcdConfig)
	manager := event.NewManager()
	mysqlConfig := newMysqlCfg(cfg)
	db := newGormDB(mysqlConfig)
	scheduler := extcron.NewScheduler(client, manager, db)
	return scheduler
}

func dispatcherProvider(cfg *proto.AppConfig) *dispatcher.Dispatcher {
	dispatcherConfig := newDispatcherCfg(cfg)
	etcdConfig := newEtcdCfg(cfg)
	client := newEtcdCli(etcdConfig)
	manager := event.NewManager()
	mysqlConfig := newMysqlCfg(cfg)
	db := newGormDB(mysqlConfig)
	dispatcherDispatcher := dispatcher.NewDispatcher(dispatcherConfig, client, manager, db)
	return dispatcherDispatcher
}

func sentryProvider(cfg *proto.AppConfig) *extcron.Sentry {
	etcdConfig := newEtcdCfg(cfg)
	client := newEtcdCli(etcdConfig)
	mysqlConfig := newMysqlCfg(cfg)
	db := newGormDB(mysqlConfig)
	manager := event.NewManager()
	sentry := extcron.NewSentry(client, db, manager)
	return sentry
}
