// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: event.proto

package proto

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on PayloadRoleChanged with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PayloadRoleChanged) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PayloadRoleChanged with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PayloadRoleChangedMultiError, or nil if none found.
func (m *PayloadRoleChanged) ValidateAll() error {
	return m.validate(true)
}

func (m *PayloadRoleChanged) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OldRole

	// no validation rules for NewRole

	if len(errors) > 0 {
		return PayloadRoleChangedMultiError(errors)
	}

	return nil
}

// PayloadRoleChangedMultiError is an error wrapping multiple validation errors
// returned by PayloadRoleChanged.ValidateAll() if the designated constraints
// aren't met.
type PayloadRoleChangedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PayloadRoleChangedMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PayloadRoleChangedMultiError) AllErrors() []error { return m }

// PayloadRoleChangedValidationError is the validation error returned by
// PayloadRoleChanged.Validate if the designated constraints aren't met.
type PayloadRoleChangedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PayloadRoleChangedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PayloadRoleChangedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PayloadRoleChangedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PayloadRoleChangedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PayloadRoleChangedValidationError) ErrorName() string {
	return "PayloadRoleChangedValidationError"
}

// Error satisfies the builtin error interface
func (e PayloadRoleChangedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPayloadRoleChanged.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PayloadRoleChangedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PayloadRoleChangedValidationError{}

// Validate checks the field values on PayloadJobDispatched with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PayloadJobDispatched) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PayloadJobDispatched with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PayloadJobDispatchedMultiError, or nil if none found.
func (m *PayloadJobDispatched) ValidateAll() error {
	return m.validate(true)
}

func (m *PayloadJobDispatched) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetJob()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, PayloadJobDispatchedValidationError{
					field:  "Job",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, PayloadJobDispatchedValidationError{
					field:  "Job",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetJob()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PayloadJobDispatchedValidationError{
				field:  "Job",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for ExecId

	if len(errors) > 0 {
		return PayloadJobDispatchedMultiError(errors)
	}

	return nil
}

// PayloadJobDispatchedMultiError is an error wrapping multiple validation
// errors returned by PayloadJobDispatched.ValidateAll() if the designated
// constraints aren't met.
type PayloadJobDispatchedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PayloadJobDispatchedMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PayloadJobDispatchedMultiError) AllErrors() []error { return m }

// PayloadJobDispatchedValidationError is the validation error returned by
// PayloadJobDispatched.Validate if the designated constraints aren't met.
type PayloadJobDispatchedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PayloadJobDispatchedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PayloadJobDispatchedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PayloadJobDispatchedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PayloadJobDispatchedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PayloadJobDispatchedValidationError) ErrorName() string {
	return "PayloadJobDispatchedValidationError"
}

// Error satisfies the builtin error interface
func (e PayloadJobDispatchedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPayloadJobDispatched.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PayloadJobDispatchedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PayloadJobDispatchedValidationError{}

// Validate checks the field values on PayloadJobModified with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PayloadJobModified) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PayloadJobModified with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PayloadJobModifiedMultiError, or nil if none found.
func (m *PayloadJobModified) ValidateAll() error {
	return m.validate(true)
}

func (m *PayloadJobModified) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return PayloadJobModifiedMultiError(errors)
	}

	return nil
}

// PayloadJobModifiedMultiError is an error wrapping multiple validation errors
// returned by PayloadJobModified.ValidateAll() if the designated constraints
// aren't met.
type PayloadJobModifiedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PayloadJobModifiedMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PayloadJobModifiedMultiError) AllErrors() []error { return m }

// PayloadJobModifiedValidationError is the validation error returned by
// PayloadJobModified.Validate if the designated constraints aren't met.
type PayloadJobModifiedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PayloadJobModifiedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PayloadJobModifiedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PayloadJobModifiedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PayloadJobModifiedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PayloadJobModifiedValidationError) ErrorName() string {
	return "PayloadJobModifiedValidationError"
}

// Error satisfies the builtin error interface
func (e PayloadJobModifiedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPayloadJobModified.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PayloadJobModifiedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PayloadJobModifiedValidationError{}

// Validate checks the field values on Event with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Event) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Event with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in EventMultiError, or nil if none found.
func (m *Event) ValidateAll() error {
	return m.validate(true)
}

func (m *Event) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Type

	if all {
		switch v := interface{}(m.GetRoleChanged()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, EventValidationError{
					field:  "RoleChanged",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, EventValidationError{
					field:  "RoleChanged",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRoleChanged()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return EventValidationError{
				field:  "RoleChanged",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetJobDispatched()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, EventValidationError{
					field:  "JobDispatched",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, EventValidationError{
					field:  "JobDispatched",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetJobDispatched()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return EventValidationError{
				field:  "JobDispatched",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetJobModified()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, EventValidationError{
					field:  "JobModified",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, EventValidationError{
					field:  "JobModified",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetJobModified()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return EventValidationError{
				field:  "JobModified",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return EventMultiError(errors)
	}

	return nil
}

// EventMultiError is an error wrapping multiple validation errors returned by
// Event.ValidateAll() if the designated constraints aren't met.
type EventMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EventMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EventMultiError) AllErrors() []error { return m }

// EventValidationError is the validation error returned by Event.Validate if
// the designated constraints aren't met.
type EventValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EventValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EventValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EventValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EventValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EventValidationError) ErrorName() string { return "EventValidationError" }

// Error satisfies the builtin error interface
func (e EventValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEvent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EventValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EventValidationError{}
