// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: ezjob.proto

package proto

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcType int32

const (
	ProcType_HTTP  ProcType = 0
	ProcType_Kafka ProcType = 1
)

// Enum value maps for ProcType.
var (
	ProcType_name = map[int32]string{
		0: "HTTP",
		1: "Kafka",
	}
	ProcType_value = map[string]int32{
		"HTTP":  0,
		"Kafka": 1,
	}
)

func (x ProcType) Enum() *ProcType {
	p := new(ProcType)
	*p = x
	return p
}

func (x ProcType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcType) Descriptor() protoreflect.EnumDescriptor {
	return file_ezjob_proto_enumTypes[0].Descriptor()
}

func (ProcType) Type() protoreflect.EnumType {
	return &file_ezjob_proto_enumTypes[0]
}

func (x ProcType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcType.Descriptor instead.
func (ProcType) EnumDescriptor() ([]byte, []int) {
	return file_ezjob_proto_rawDescGZIP(), []int{0}
}

type Proc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     ProcType  `protobuf:"varint,1,opt,name=type,proto3,enum=proto.ProcType" json:"type,omitempty"`
	HttpProc *HttpProc `protobuf:"bytes,2,opt,name=http_proc,json=httpProc,proto3" json:"http_proc,omitempty"`
}

func (x *Proc) Reset() {
	*x = Proc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ezjob_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Proc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proc) ProtoMessage() {}

func (x *Proc) ProtoReflect() protoreflect.Message {
	mi := &file_ezjob_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proc.ProtoReflect.Descriptor instead.
func (*Proc) Descriptor() ([]byte, []int) {
	return file_ezjob_proto_rawDescGZIP(), []int{0}
}

func (x *Proc) GetType() ProcType {
	if x != nil {
		return x.Type
	}
	return ProcType_HTTP
}

func (x *Proc) GetHttpProc() *HttpProc {
	if x != nil {
		return x.HttpProc
	}
	return nil
}

type HttpProc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url     string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Payload string `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *HttpProc) Reset() {
	*x = HttpProc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ezjob_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HttpProc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpProc) ProtoMessage() {}

func (x *HttpProc) ProtoReflect() protoreflect.Message {
	mi := &file_ezjob_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpProc.ProtoReflect.Descriptor instead.
func (*HttpProc) Descriptor() ([]byte, []int) {
	return file_ezjob_proto_rawDescGZIP(), []int{1}
}

func (x *HttpProc) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HttpProc) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type ProcPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type ProcType         `protobuf:"varint,1,opt,name=type,proto3,enum=proto.ProcType" json:"type,omitempty"`
	Http *HttpProcPayload `protobuf:"bytes,2,opt,name=http,proto3" json:"http,omitempty"`
}

func (x *ProcPayload) Reset() {
	*x = ProcPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ezjob_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcPayload) ProtoMessage() {}

func (x *ProcPayload) ProtoReflect() protoreflect.Message {
	mi := &file_ezjob_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcPayload.ProtoReflect.Descriptor instead.
func (*ProcPayload) Descriptor() ([]byte, []int) {
	return file_ezjob_proto_rawDescGZIP(), []int{2}
}

func (x *ProcPayload) GetType() ProcType {
	if x != nil {
		return x.Type
	}
	return ProcType_HTTP
}

func (x *ProcPayload) GetHttp() *HttpProcPayload {
	if x != nil {
		return x.Http
	}
	return nil
}

type HttpProcPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskName    string `protobuf:"bytes,1,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	ExecutionId int32  `protobuf:"varint,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Payload     string `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *HttpProcPayload) Reset() {
	*x = HttpProcPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ezjob_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HttpProcPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpProcPayload) ProtoMessage() {}

func (x *HttpProcPayload) ProtoReflect() protoreflect.Message {
	mi := &file_ezjob_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpProcPayload.ProtoReflect.Descriptor instead.
func (*HttpProcPayload) Descriptor() ([]byte, []int) {
	return file_ezjob_proto_rawDescGZIP(), []int{3}
}

func (x *HttpProcPayload) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *HttpProcPayload) GetExecutionId() int32 {
	if x != nil {
		return x.ExecutionId
	}
	return 0
}

func (x *HttpProcPayload) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type Job struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: param:"name"
	Name     string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" param:"name"`
	Schedule string   `protobuf:"bytes,2,opt,name=schedule,proto3" json:"schedule,omitempty"`
	Owners   []string `protobuf:"bytes,3,rep,name=owners,proto3" json:"owners,omitempty"`
	Mode     string   `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`
	Proc     *Proc    `protobuf:"bytes,5,opt,name=proc,proto3" json:"proc,omitempty"`
}

func (x *Job) Reset() {
	*x = Job{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ezjob_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_ezjob_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_ezjob_proto_rawDescGZIP(), []int{4}
}

func (x *Job) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Job) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *Job) GetOwners() []string {
	if x != nil {
		return x.Owners
	}
	return nil
}

func (x *Job) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *Job) GetProc() *Proc {
	if x != nil {
		return x.Proc
	}
	return nil
}

type ListJobReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ListJobReq) Reset() {
	*x = ListJobReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ezjob_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListJobReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobReq) ProtoMessage() {}

func (x *ListJobReq) ProtoReflect() protoreflect.Message {
	mi := &file_ezjob_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobReq.ProtoReflect.Descriptor instead.
func (*ListJobReq) Descriptor() ([]byte, []int) {
	return file_ezjob_proto_rawDescGZIP(), []int{5}
}

func (x *ListJobReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListJobRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tasks []*Job `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
}

func (x *ListJobRsp) Reset() {
	*x = ListJobRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ezjob_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListJobRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobRsp) ProtoMessage() {}

func (x *ListJobRsp) ProtoReflect() protoreflect.Message {
	mi := &file_ezjob_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobRsp.ProtoReflect.Descriptor instead.
func (*ListJobRsp) Descriptor() ([]byte, []int) {
	return file_ezjob_proto_rawDescGZIP(), []int{6}
}

func (x *ListJobRsp) GetTasks() []*Job {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type DelJobReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *DelJobReq) Reset() {
	*x = DelJobReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ezjob_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelJobReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelJobReq) ProtoMessage() {}

func (x *DelJobReq) ProtoReflect() protoreflect.Message {
	mi := &file_ezjob_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelJobReq.ProtoReflect.Descriptor instead.
func (*DelJobReq) Descriptor() ([]byte, []int) {
	return file_ezjob_proto_rawDescGZIP(), []int{7}
}

func (x *DelJobReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RunJobReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Payload string `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *RunJobReq) Reset() {
	*x = RunJobReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ezjob_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunJobReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunJobReq) ProtoMessage() {}

func (x *RunJobReq) ProtoReflect() protoreflect.Message {
	mi := &file_ezjob_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunJobReq.ProtoReflect.Descriptor instead.
func (*RunJobReq) Descriptor() ([]byte, []int) {
	return file_ezjob_proto_rawDescGZIP(), []int{8}
}

func (x *RunJobReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RunJobReq) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type ReportReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobName     string `protobuf:"bytes,1,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	Status      string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Log         string `protobuf:"bytes,3,opt,name=log,proto3" json:"log,omitempty"`
	ExecutionId int32  `protobuf:"varint,4,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
}

func (x *ReportReq) Reset() {
	*x = ReportReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ezjob_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportReq) ProtoMessage() {}

func (x *ReportReq) ProtoReflect() protoreflect.Message {
	mi := &file_ezjob_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportReq.ProtoReflect.Descriptor instead.
func (*ReportReq) Descriptor() ([]byte, []int) {
	return file_ezjob_proto_rawDescGZIP(), []int{9}
}

func (x *ReportReq) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *ReportReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReportReq) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

func (x *ReportReq) GetExecutionId() int32 {
	if x != nil {
		return x.ExecutionId
	}
	return 0
}

var File_ezjob_proto protoreflect.FileDescriptor

var file_ezjob_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x65, 0x7a, 0x6a, 0x6f, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x59, 0x0a, 0x04, 0x50, 0x72,
	0x6f, 0x63, 0x12, 0x23, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2c, 0x0a, 0x09, 0x68, 0x74, 0x74, 0x70, 0x5f,
	0x70, 0x72, 0x6f, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x48, 0x74, 0x74, 0x70, 0x50, 0x72, 0x6f, 0x63, 0x52, 0x08, 0x68, 0x74, 0x74,
	0x70, 0x50, 0x72, 0x6f, 0x63, 0x22, 0x36, 0x0a, 0x08, 0x48, 0x74, 0x74, 0x70, 0x50, 0x72, 0x6f,
	0x63, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x72, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x5e, 0x0a,
	0x0b, 0x50, 0x72, 0x6f, 0x63, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x23, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x2a, 0x0a, 0x04, 0x68, 0x74, 0x74, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x74, 0x74, 0x70, 0x50, 0x72, 0x6f, 0x63,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x04, 0x68, 0x74, 0x74, 0x70, 0x22, 0x6b, 0x0a,
	0x0f, 0x48, 0x74, 0x74, 0x70, 0x50, 0x72, 0x6f, 0x63, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x12, 0x1b, 0x0a, 0x09, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x61, 0x73, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a,
	0x0c, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0b, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0xc6, 0x01, 0x0a, 0x03, 0x4a,
	0x6f, 0x62, 0x12, 0x2b, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x17, 0xfa, 0x42, 0x14, 0x72, 0x12, 0x18, 0x20, 0x32, 0x0e, 0x5e, 0x5b, 0x61, 0x2d, 0x7a,
	0x41, 0x2d, 0x5a, 0x30, 0x2d, 0x39, 0x5d, 0x2b, 0x24, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x23, 0x0a, 0x08, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x08, 0x73, 0x63, 0x68, 0x65,
	0x64, 0x75, 0x6c, 0x65, 0x12, 0x22, 0x0a, 0x06, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x09, 0x42, 0x0a, 0xfa, 0x42, 0x07, 0x92, 0x01, 0x04, 0x08, 0x01, 0x18, 0x01,
	0x52, 0x06, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x73, 0x12, 0x28, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x42, 0x14, 0xfa, 0x42, 0x11, 0x72, 0x0f, 0x52, 0x06, 0x73,
	0x69, 0x6e, 0x67, 0x6c, 0x65, 0x52, 0x05, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x52, 0x04, 0x6d, 0x6f,
	0x64, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x70, 0x72, 0x6f, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x52, 0x04, 0x70,
	0x72, 0x6f, 0x63, 0x22, 0x39, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x4a, 0x6f, 0x62, 0x52, 0x65,
	0x71, 0x12, 0x2b, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x17, 0xfa, 0x42, 0x14, 0x72, 0x12, 0x18, 0x20, 0x32, 0x0e, 0x5e, 0x5b, 0x61, 0x2d, 0x7a, 0x41,
	0x2d, 0x5a, 0x30, 0x2d, 0x39, 0x5d, 0x2b, 0x24, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2e,
	0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x4a, 0x6f, 0x62, 0x52, 0x73, 0x70, 0x12, 0x20, 0x0a, 0x05,
	0x74, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x4a, 0x6f, 0x62, 0x52, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x22, 0x3a,
	0x0a, 0x09, 0x44, 0x65, 0x6c, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x12, 0x2d, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x19, 0xfa, 0x42, 0x16, 0x72, 0x14,
	0x10, 0x01, 0x18, 0x20, 0x32, 0x0e, 0x5e, 0x5b, 0x61, 0x2d, 0x7a, 0x41, 0x2d, 0x5a, 0x30, 0x2d,
	0x39, 0x5d, 0x2b, 0x24, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x52, 0x0a, 0x09, 0x52, 0x75,
	0x6e, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x12, 0x2b, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x17, 0xfa, 0x42, 0x14, 0x72, 0x12, 0x18, 0x20, 0x32, 0x0e,
	0x5e, 0x5b, 0x61, 0x2d, 0x7a, 0x41, 0x2d, 0x5a, 0x30, 0x2d, 0x39, 0x5d, 0x2b, 0x24, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0xb2,
	0x01, 0x0a, 0x09, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x12, 0x32, 0x0a, 0x08,
	0x6a, 0x6f, 0x62, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x17,
	0xfa, 0x42, 0x14, 0x72, 0x12, 0x18, 0x20, 0x32, 0x0e, 0x5e, 0x5b, 0x61, 0x2d, 0x7a, 0x41, 0x2d,
	0x5a, 0x30, 0x2d, 0x39, 0x5d, 0x2b, 0x24, 0x52, 0x07, 0x6a, 0x6f, 0x62, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x29, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x11, 0xfa, 0x42, 0x0e, 0x72, 0x0c, 0x52, 0x04, 0x73, 0x75, 0x63, 0x63, 0x52, 0x04, 0x66,
	0x61, 0x69, 0x6c, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x03, 0x6c,
	0x6f, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x08, 0xfa, 0x42, 0x05, 0x72, 0x03, 0x18,
	0x80, 0x08, 0x52, 0x03, 0x6c, 0x6f, 0x67, 0x12, 0x2a, 0x0a, 0x0c, 0x65, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x42, 0x07, 0xfa,
	0x42, 0x04, 0x1a, 0x02, 0x20, 0x00, 0x52, 0x0b, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x2a, 0x1f, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x63, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x08, 0x0a, 0x04, 0x48, 0x54, 0x54, 0x50, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x4b, 0x61, 0x66,
	0x6b, 0x61, 0x10, 0x01, 0x32, 0x3b, 0x0a, 0x05, 0x45, 0x7a, 0x4a, 0x6f, 0x62, 0x12, 0x32, 0x0a,
	0x06, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6a, 0x61, 0x63, 0x6b, 0x69, 0x65, 0x38, 0x74, 0x61, 0x6f, 0x2f, 0x65, 0x7a, 0x6a, 0x6f, 0x62,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ezjob_proto_rawDescOnce sync.Once
	file_ezjob_proto_rawDescData = file_ezjob_proto_rawDesc
)

func file_ezjob_proto_rawDescGZIP() []byte {
	file_ezjob_proto_rawDescOnce.Do(func() {
		file_ezjob_proto_rawDescData = protoimpl.X.CompressGZIP(file_ezjob_proto_rawDescData)
	})
	return file_ezjob_proto_rawDescData
}

var file_ezjob_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ezjob_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_ezjob_proto_goTypes = []interface{}{
	(ProcType)(0),           // 0: proto.ProcType
	(*Proc)(nil),            // 1: proto.Proc
	(*HttpProc)(nil),        // 2: proto.HttpProc
	(*ProcPayload)(nil),     // 3: proto.ProcPayload
	(*HttpProcPayload)(nil), // 4: proto.HttpProcPayload
	(*Job)(nil),             // 5: proto.Job
	(*ListJobReq)(nil),      // 6: proto.ListJobReq
	(*ListJobRsp)(nil),      // 7: proto.ListJobRsp
	(*DelJobReq)(nil),       // 8: proto.DelJobReq
	(*RunJobReq)(nil),       // 9: proto.RunJobReq
	(*ReportReq)(nil),       // 10: proto.ReportReq
	(*empty.Empty)(nil),     // 11: google.protobuf.Empty
}
var file_ezjob_proto_depIdxs = []int32{
	0,  // 0: proto.Proc.type:type_name -> proto.ProcType
	2,  // 1: proto.Proc.http_proc:type_name -> proto.HttpProc
	0,  // 2: proto.ProcPayload.type:type_name -> proto.ProcType
	4,  // 3: proto.ProcPayload.http:type_name -> proto.HttpProcPayload
	1,  // 4: proto.Job.proc:type_name -> proto.Proc
	5,  // 5: proto.ListJobRsp.tasks:type_name -> proto.Job
	10, // 6: proto.EzJob.Report:input_type -> proto.ReportReq
	11, // 7: proto.EzJob.Report:output_type -> google.protobuf.Empty
	7,  // [7:8] is the sub-list for method output_type
	6,  // [6:7] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_ezjob_proto_init() }
func file_ezjob_proto_init() {
	if File_ezjob_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ezjob_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Proc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ezjob_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HttpProc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ezjob_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ezjob_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HttpProcPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ezjob_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Job); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ezjob_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListJobReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ezjob_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListJobRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ezjob_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelJobReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ezjob_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunJobReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ezjob_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ezjob_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ezjob_proto_goTypes,
		DependencyIndexes: file_ezjob_proto_depIdxs,
		EnumInfos:         file_ezjob_proto_enumTypes,
		MessageInfos:      file_ezjob_proto_msgTypes,
	}.Build()
	File_ezjob_proto = out.File
	file_ezjob_proto_rawDesc = nil
	file_ezjob_proto_goTypes = nil
	file_ezjob_proto_depIdxs = nil
}
